version: '2'
services:
    smartlpc-app:
        image: smartlpc
        external_links:
            - smartlpc-mysql:mysql
            - smartlpc-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/smartlpc?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    smartlpc-mysql:
        extends:
            file: mysql.yml
            service: smartlpc-mysql
    smartlpc-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: smartlpc-elasticsearch
